name: workflow-run triggered

on:
  workflow_run:
    workflows:
      - "test"
      - \!trigger\?
      - '\!trigger-3'
    types:
      - in_progress

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
